//
//  AsyncCachedImage
//
//  Copyright © 2026 Jan-Hendrik Damerau.
//  https://github.com/uaremad/AsyncCachedImage
//
//  Licensed under the MIT License
//  Free to use without restrictions. See LICENSE file for full terms.
//

@preconcurrency import ProjectDescription

/// AsyncCachedImage workspace configuration.
///
/// This workspace contains a single project with the Demo app and Core library.
/// Configured to prevent automatic scheme generation for full control over build schemes.
///
/// ## Workspace Structure
///
/// ```
/// AsyncCachedImage.xcworkspace
/// └── AsyncCachedImage Project (.)
///     ├── Demo App (App/)
///     └── Core Library (Core/)
/// ```
///
/// ## Scheme Configuration
///
/// All schemes are defined in `Project.swift` and shared across the team.
/// Automatic workspace schemes are disabled to prevent:
/// - Duplicate schemes
/// - Unintended scheme modifications
/// - Workspace-level scheme generation
///
/// ## Generation Options
///
/// - **enableAutomaticXcodeSchemes**: Disabled
///   - Prevents Xcode from automatically creating schemes
///   - Ensures consistent scheme configuration across team
///
/// - **autogeneratedWorkspaceSchemes**: Disabled
///   - Prevents workspace-level scheme generation
///   - All schemes are project-level only
///
/// ## Usage
///
/// Generate the workspace:
/// ```bash
/// tuist generate
/// ```
///
/// Open the workspace:
/// ```bash
/// open AsyncCachedImage.xcworkspace
/// ```
///
/// - Important: Never manually modify schemes in Xcode. All scheme changes
///   should be made in `Project.swift` and regenerated with Tuist.
///
/// - SeeAlso: `Project.swift` for scheme definitions
let workspace = Workspace(
    name: "AsyncCachedImage",
    projects: ["."],
    schemes: [],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled
    )
)
